# Generated by Django 3.0.8 on 2020-07-28 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(max_length=50)),
                ('date', models.DateTimeField()),
                ('attendees', models.ManyToManyField(blank=True, related_name='events_joined', to=settings.AUTH_USER_MODEL)),
                ('related_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
