# Generated by Django 3.0.8 on 2020-07-28 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_groups', '0002_auto_20200727_1258'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='related_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_events', to='workout_groups.WorkoutGroup'),
        ),
    ]
