# Generated by Django 3.0.8 on 2020-08-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout_groups', '0001_initial'),
        ('events', '0002_auto_20200807_1407'),
        ('comments', '0002_auto_20200807_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='related_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='related_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_comments', to='workout_groups.WorkoutGroup'),
        ),
    ]
